name: Towny
main: ca.xshade.bukkit.towny.Towny
version: 0.69
author: Shade, Modified by FuzzeWuzze
website: http://towny.xshade.ca
description: >
    Resident-Town-Nation heirarchy combined with a grid based
    protection system. Including a war event.
commands:
    towny:
        description: Basic towny commands.